pipeline {
    agent any
    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/Arunkumar1418/devopscourse.git'
            }
        }
        stage('Docker Login') {
            steps {
                 withCredentials([string(credentialsId: 'DockerHubPasswd', variable: 'dockerHubPasswd')]) {
                   sh 'docker login -u arunkumar1418  -p ${dockerHubPasswd}'               
                 }
            }
        }
        stage('Docker Build') {
            steps {
                //sh 'docker build -t arunkumar1418/jenkinstest ./pushdockerimage/' (this will use the tag latest)
		sh 'docker build -t arunkumar1418/jenkinstest:$BUILD_NUMBER ./pushdockerimage/'
            }
        }
        stage('Docker Push') {
            steps {
		//sh 'docker push raj80dockerid/jenkinstest' (this will use the tag latest)    
                sh 'docker push arunkumar1418/jenkinstest:$BUILD_NUMBER'
             }
        }
        stage('Trivy Scan') {
            steps {
                withCredentials([string(credentialsId: 'DockerHubPasswd', variable: 'dockerHubPasswd')]) {
                   sh 'docker login -u arunkumar1418  -p ${dockerHubPasswd}'
                   // This step is to scan the docker image that we have build   
                   sh 'docker run aquasec/trivy image arunkumar1418/jenkinstest:$BUILD_NUMBER'               
                 }
             }
        }
    }
    post {
		always {
			sh 'docker logout'
		}
    }
}

